version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
     
      - run: 
          name: ant retrive
          command: ant -lib lib/ -buildfile build.xml retrive
      - run: 
          name: ant push
          command: ant -lib lib/ -buildfile build.xml push
