version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: ant -lib lib/ -buildfile build.xml
          command: ant -lib lib/ -buildfile build.xml
      - run: 
          name: ant retrive
          command: ant retrive
      - run: 
          name: ant push
          command: ant push
