version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: ant push
          command: ant push
          
          
          
          
          
          
          

